### ISSUE TITLE
Unknown file "QuickTest.mscp"

### ISSUE THREAD

**Issue by Arcnor** [JoeStrout/miniscript#13]
Hi there,

First of all, I think it's very cool that you've open sourced MiniScript, it looks really nice, thanks for that!

I've tried running the tests (using `Program.cs`) and it looks like it's trying to load a file called "QuickTest.mscp" which is nowhere to be found.

Not sure if the file should be there, or that line should be removed, hence this issue.

Thanks!

**Comment by JoeStrout** [comment]
Ah, good catch — the C# main program will try to load and run this file.  I use it to quickly test whatever I happen to be working on each day; that's why I didn't commit it to the archive.  If I have a test I want to keep, I put it into TestSuite.txt (which _is_ in the repo).

But the main program should certainly detect that QuickTest.mscp (so old is this file, it's from before I settled on ".ms" as a file extension!) is missing, and handle in gracefully.  Feel free to make that change and issue a pull request!  You could be our first, a badge of honor no one can ever take from you.  :)

**Comment by Arcnor** [comment]
Good point, the honor shall be mine!

More seriously, maybe the right thing to do will be having that list of
files to run as arguments? To remove those magic constants from the code
itself, mainly.

I can open the PR just with the file detection, but it still feels like a
hack 🙂.
