### ISSUE TITLE
Incorrect behavior of `pop`

### ISSUE THREAD

**Issue by Arcnor** [JoeStrout/miniscript#19]
This code:

```
d = {1:"one", 2:"two", 3:"three"}
print pop(d)
```

...prints `1`, but I think it should return `one` instead (unless it's on purpose, of course)? So `pop` is returning the first key on a map, and not its value.

**Comment by Arcnor** [comment]
And also (just so I don't bog you down with issues) I think it should return the last one (so `three` instead). The code says "it returns the last item" but then it proceeds to do `map.map.Keys.First()`, which ends up having the same behavior as `pull`

**Comment by JoeStrout** [comment]
It's definitely correct to return the key, not the value.  The documented behavior is:

> .pop remove and return an arbitrary key from self

There are a couple reasons why this behavior was chosen.  First, it lets you use a map like a hash set, `.push`ing keys in and `pop`ping them back out (all the values are 1 in this case).  Second, if for some reason you're popping items out of an arbitrary map, then given the key, you can always find the value, but the reverse is not true.  (A possible alternative would be to return a key/value pair, like what you get when you iterate over a map with `for`, but that seems heavy-handed in this case.)

Also, as for which one you get... well it's just not correct to care.  It's documented to return an _arbitrary_ key.  And the order of map.Keys (presented to the user as map.indexes) is also arbitrary.  You should shouldn't expect any particular order to any of these things.  You _can_ expect it not to waste any time about it, though.  So it's implemented under the hood with `map.map.Keys.First()` because I expect that to be faster than `Keys.Last()`.

(And yes, if you call `pull(d)`, it happens to be functionally equivalent to `pop(d)` or `d.pop`.  That's why `pull` is not presented as a member function on maps; it's redundant, and `pop` makes more sense.)

**Comment by JoeStrout** [comment]
(But I'm giving you thumbs-up for filing the issue anyway.  Thank you for caring enough to do so, and please keep them coming!)

**Comment by Arcnor** [comment]
Sure, no worries! I "found" this when working on this other thing, I'm not sure if you get notifications from the forums, so linking here just in case: https://forums.miniscript.org/d/38-kotlin-version-of-miniscript and https://forums.miniscript.org/d/39-miniscript-grammar .

Thanks!

**Comment by JoeStrout** [comment]
I don't get automatic notifications — though I do check the forums frequently, but was out of town (and out of touch) all weekend.  So thanks for pointing these out.  Fantastic work!
