### ISSUE TITLE
Miniscript allow you to override standard functions

### ISSUE THREAD

**Issue by andreakarasho** [JoeStrout/miniscript#21]
For example:
![image](https://user-images.githubusercontent.com/20810422/66042190-1a06a980-e51c-11e9-8699-fabd40dd2d1e.png)

That is really incovenient to allow because i can replace useful methods unwittingly.
This behaviour should be expected when you use Intrisic to replace/add new functions imho.

**Comment by JoeStrout** [comment]
This is true.  But in a small script or interactive environment, this is not too likely to cause problems; and in a big script/program, you should probably be defining most of your function inside classes or modules (i.e. maps), so the odds of a collision are much smaller.

And at least (unlike _some_ scripting languages we could mention) variables are all local by default rather than global, so you're not going to inadvertently clobber something with any local variable inside a method.

**Comment by JoeStrout** [comment]
But if you are embedding MiniScript in your own code, and want to make the intrinsics un-overridable, I believe you could do this via the assignOverride handler.  Maybe contact me in the forums or via the support email, and I'll help you with that.

**Comment by JoeStrout** [comment]
OK, the default behavior is as intended, but you can now override it by using `assignOverride`.  Example:

```
        Interpreter repl = new Interpreter();
        repl.implicitOutput = repl.standardOutput;
        repl.Compile();
        repl.SetGlobalValue("foo", new ValNumber(42));
        repl.vm.globalContext.variables.assignOverride = (key, value) => {
            Console.WriteLine("Assigning " + value + " to " + key + ", eh?!");
            return key.ToString() == "foo";   // (disallow assignment to foo
        };

        while (true) {
            Console.Write(repl.NeedMoreInput() ? ">>> " : "> ");
            string inp = Console.ReadLine();
            if (inp == null) break;
            repl.REPL(inp);
        }
```
