### ISSUE TITLE
[QoL] range(min, max): max value should not be included

### ISSUE THREAD

**Issue by andreakarasho** [JoeStrout/miniscript#22]
Much readable, less space, less chars, more intuitive:

```mylist = [20, 8, 2, 3, 158]
for i in range(0, len(mylist))
    print mylist[i]
end for
```

Than actual

```mylist = [20, 8, 2, 3, 158]
for i in range(0, len(mylist) - 1)
    print mylist[i]
end for
```

**Comment by JoeStrout** [comment]
Even better:
```for i in mylist.indexes
    print mylist[i]
end for```

**Comment by JoeStrout** [comment]
So we thought a lot about how range() should behave, and finally settled on the current behavior for a couple of reasons:

1. It's less surprising to new programmers
2. It lets you make, say, a counter from 1 to 10 by doing range(1,10) rather than range(1,10.1) or range(1,11)
3. It's the only behavior that makes sense in general with floating-point numbers, e.g. range(0.5, 0.8, 0.1), and in MiniScript _all_ numbers are floating-point
4. As noted above, when you're trying to iterate over a collection, there are better ways of doing that anyway.

I do understand this behavior may be surprising to people that have done a lot of coding in other languages, though, where the semi-open interval is standard and convenient for integer ranges.

**Comment by andreakarasho** [comment]
Make sense thanks
