### ISSUE TITLE
Single line if-else inconsistent behavior

### ISSUE THREAD

**Issue by juh9870** [JoeStrout/miniscript#86]
Single line `if ... then` allows any single line expression to follow it, including chained `if`s, like this:
```js
if 1 then if 2 then if 3 then print "4" else print "5" else print "6" else print "7"
```
> This compiles

But this is not the same for single line `else`, which doesn't allow nesting `if`s
```js
if 1 then print 1 else if 2 then print 2
```
> Compiler Error: got Keyword(else if) where number, string, or identifier is required [line 1]

**Comment by JoeStrout** [comment]
While legal, this seems like an ill-advised abuse of the syntax.  But I agree it seems inconsistent as is.

If the fix is as simple as treating an `else if` keyword as separate `else` (followed by `if`) keywords in the context of a single-line `if`, then OK, let's fix it.  If it's more involved than that, let's defer until a later/larger update.
